version: '3'
volumes:
  pg_data:
    name: pg_data
  static:
    name: static
  media:
    name: media
services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: masimn/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media
    depends_on:
      - db
  frontend:
    container_name: frontend
    env_file: .env
    image: masimn/foodgram_frontend
    volumes:
      - static:/static/
    command: cp -r /app/build/. /static/

  gateway:
    container_name: gateway
    image: masimn/foodgram_nginx
    volumes:
        - static:/static/
        - media:/app/media

    ports:
      - 8000:80
