# Generated by Django 3.2 on 2023-09-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post',
            new_name='receipts',
        ),
    ]
