# Generated by Django 3.2 on 2023-09-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='user_favorite',
        ),
    ]
