# Generated by Django 3.2 on 2023-09-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
