# Generated by Django 3.2 on 2023-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridients',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingridients',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingridients',
            name='measurement_unit',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingridients',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
