# Generated by Django 2.2.19 on 2023-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20230831_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='unit',
            field=models.SmallIntegerField(),
        ),
    ]
