# Generated by Django 3.2 on 2023-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20230906_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridients',
            new_name='Ingredients',
        ),
    ]
