# Generated by Django 3.2 on 2023-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_ingridients_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='receipts',
            options={'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='receipts',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
    ]
